name: Pytest CI 🔎

on:
  workflow_call

jobs:
  test:
    runs-on: ubuntu-22.04

    services:
      mysql:
        image: mysql:8.0.33
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        options: >-
          --health-cmd "mysqladmin ping -h localhost"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python 3.7
        uses: actions/setup-python@v4
        with:
          python-version: 3.7

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Wait for MySQL to be healthy
      - name: Wait for MySQL
        run: |
          for i in {1..30}; do
            if docker exec $(docker ps -q -f ancestor=mysql:8.0.33) mysqladmin ping -h "localhost" --silent; then
              echo "MySQL is up and running"
              break
            fi
            sleep 1
          done

      # Step 5: Run Pytest
      - name: Run Tests with Pytest
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_DB: test_db
          FLASK_ENV: local
          SECRET_KEY: abcd123456
          SQLALCHEMY_TRACK_MODIFICATIONS: false
        run: |
          pytest tests/
