name: Staging 🚀

on:
  workflow_call:

jobs:

  detect-staging-label:
    runs-on: ubuntu-latest
    outputs:
      label_found: ${{ env.LABEL_FOUND }}
    steps:
      - name: Check if 'S3_BUCKET_PATH' repo variable is set
        run: |
          if [ -z "${{ vars.S3_BUCKET_PATH }}" ]; then
            echo "S3_BUCKET_PATH repo variable is not set. Exiting workflow."
            exit 1
          fi
      - name: Check for 'staging' label
        id: check_label
        run: |
          if [[ "${{ contains(join(github.event.pull_request.labels.*.name, ','), 'staging') }}" == "true" ]]; then
            echo "LABEL_FOUND=true" >> $GITHUB_ENV
          else
            echo "No 'staging' label found. Skipping the workflow."
            echo "LABEL_FOUND=false" >> $GITHUB_ENV
          fi
      

  build-and-deploy:
    needs: detect-staging-label
    runs-on: ubuntu-latest
    if: needs.detect-staging-label.outputs.label_found == 'true'
    name: 'Build and Deploy'
    outputs:
      webhook_id: ${{ 'test' }}
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: Set config variables
        id: configs
        run: |
          echo "WEBHOOK_ID=${{ secrets.SLACK_FRONTEND_APPS_BLD_ALRT_STAGING }}" >> $GITHUB_ENV
          echo "ACCOUNT_ID=${{ secrets.AWS_STAGING_ACCOUNT_ID }}" >> $GITHUB_ENV
          echo "BUCKET=${{ vars.S3_STAGING_BUCKET || secrets.S3_STAGING_APPS_BUCKET }}" >> $GITHUB_ENV
          echo "DIST_ID=${{ secrets.CLOUDFRONT_STAGING_DISTRIBUTION_ID || secrets.CLOUDFRONT_STAGING_APPS_DISTRIBUTION_ID }}" >> $GITHUB_ENV
          echo "DEPLOY_BRANCH_NAME=staging" >> $GITHUB_ENV
          echo "FOLDER=build" >> $GITHUB_ENV
          echo "INVALIDATION=${{ vars.S3_BUCKET_PATH }}" >> $GITHUB_ENV
          echo "DELETE_REMOVED=**" >> $GITHUB_ENV

      - name: New build Started
        uses: 8398a7/action-slack@v3
        with:
          text: 'New Build and Deploy Started for ${{ github.event.repository.name }} 🚀'
          status: 'cancelled'
          author_name: 'Frontend Build and Deploy'
          icon_emoji: ':rocket:'
        env:
          SLACK_WEBHOOK_URL: ${{ env.WEBHOOK_ID }}

      - name: Checkout PR code
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Reconfigure git to use HTTP authentication
        run: |
          git config --global url."https://github.com/".insteadOf ssh://git@github.com/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: 'arn:aws:iam::${{ env.ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_TO_DEPLOY_FRONTEND_APPS }}'
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: |
          npm ci

      - name: Build the project
        run: |
          npm run deploy --branch_name=${{ env.DEPLOY_BRANCH_NAME }}

      - name: Deploy to S3 bucket
        uses: reggionick/s3-deploy@v3
        with:
            folder: ${{ env.FOLDER }}
            bucket: ${{ env.BUCKET }}
            bucket-region: ${{ secrets.AWS_DEFAULT_REGION }}
            dist-id: ${{ env.DIST_ID }}
            invalidation: ${{ env.INVALIDATION }}
            delete-removed: ${{ env.DELETE_REMOVED }}
            no-cache: true
            private: true

  send-workflow-success:
    needs: [build-and-deploy, detect-staging-label]
    runs-on: ubuntu-latest
    if: needs.detect-staging-label.outputs.label_found == 'true' && success()
    name: 'Send success notification'
    permissions:
      contents: read
      actions: read
    steps:
      - name: Send success notification
        uses: 8398a7/action-slack@v3
        with:
          author_name: 'Frontend Build and Deploy'
          status: 'success'
          text: '${{ github.event.repository.name }} Frontend App Build and Deploy Succeeded ✅'
          fields: repo,message,commit,author,eventName,ref,workflow,job
          icon_emoji: '✅'
        env:
          SLACK_WEBHOOK_URL: ${{ needs.build-and-deploy.outputs.webhook_id }}

  send-workflow-failure:
    runs-on: ubuntu-latest
    name: 'Send fail notification'
    permissions:
      contents: read
      actions: read
    needs: [build-and-deploy, detect-staging-label]
    if: needs.detect-staging-label.outputs.label_found == 'true' && failure()
    steps:
      - name: Send fail notification
        uses: 8398a7/action-slack@v3
        with:
          author_name: 'Frontend Build and Deploy'
          mention: 'here'
          status: 'failure'
          text: '${{ github.event.repository.name }} Frontend App Build or Deploy Failed 🔴'
          fields: repo,message,commit,author,eventName,ref,workflow,job
          icon_emoji: '🔴'
        env:
          SLACK_WEBHOOK_URL: ${{ needs.build-and-deploy.outputs.webhook_id }}
