# greeter.yml
name: Reusable workflow example

on:
  workflow_call:
    inputs:
      username:
        description: Username for the workflow
        required: true
        type: string
      repo:
        description: >
          Repository to check out.
          Include a personal access token (PAT) with repo scope for private repos.
        required: true
        type: string
      environment:
        required: false
        type: string
        default: development
    secrets:
      personal-access-token:
        description: GitHub Personal Access Token (PAT) with necessary scopes
        required: false

jobs:
  greeter:
    name: Greet the user
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ inputs.repo }}
          token: ${{ secrets.personal-access-token }}
      - run: |
          echo 'Hello, ${{ inputs.username }}!' \
            'The repo ${{ inputs.repo }} was checked out.' \
            'This is the ${{ inputs.environment }} environment.'
