name: Develop 🚀

on:
  workflow_call:
jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    name: 'Build And Deploy'
    permissions:
      id-token: write	
      contents: read
      actions: read
    steps:

      - name: Set S3 variables
        id: S3_variables
        run: |
          if  [[ "${{ github.repository }}" == "WeDeliverGitHub/captainServiceFrontend" ]] ; then
            echo "##[set-output name=folder;]$(echo "build" )"
            echo "##[set-output name=bucket;]$(echo "${{ secrets.S3_DEV_APPS_BUCKET }}/captain")"
            echo "##[set-output name=invalidation;]$(echo '/')"
            echo "##[set-output name=delete-removed;]$(echo 'captain/**')"
          else
            echo "##[set-output name=folder;]$(echo "dist" )"
            echo "##[set-output name=bucket;]$(echo ${{ secrets.S3_DEV_APPS_BUCKET }}/apps/${{ secrets.APP_FOLDER_NAME }})"
            echo "##[set-output name=invalidation;]$(echo '/apps/${{ secrets.APP_FOLDER_NAME }}')"
            echo "##[set-output name=delete-removed;]$(echo 'apps/${{ secrets.APP_FOLDER_NAME }}/**')"
          fi

      - name: print S3 variables		  
        run: |
          echo "${{ steps.S3_variables.outputs.folder }}"
		  echo "${{ steps.S3_variables.outputs.bucket }}"